/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculadora;

/**
 *
 * @author Souza & Vilani
 */
public class JanelaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form JanelaCalculadora
     */
    public JanelaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPainel = new javax.swing.JTextPane();
        apaga = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        soma = new javax.swing.JButton();
        menos = new javax.swing.JButton();
        multiplica = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        porcentagem = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        exibir = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem6 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem7 = new javax.swing.JRadioButtonMenuItem();
        jMenu4 = new javax.swing.JMenu();
        editar = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        ajuda = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        Sobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        getContentPane().setLayout(null);

        txtPainel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtPainel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jScrollPane1.setViewportView(txtPainel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 20, 250, 60);

        apaga.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        apaga.setText("C");
        apaga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apagaMouseClicked(evt);
            }
        });
        getContentPane().add(apaga);
        apaga.setBounds(130, 140, 50, 50);

        btn0.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn0.setText("0");
        btn0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn0MouseClicked(evt);
            }
        });
        getContentPane().add(btn0);
        btn0.setBounds(30, 340, 100, 50);

        btn1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn1.setText("1");
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
        });
        getContentPane().add(btn1);
        btn1.setBounds(30, 290, 50, 48);

        btn2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn2.setText("2");
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
        });
        getContentPane().add(btn2);
        btn2.setBounds(80, 290, 50, 48);

        btn3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn3.setText("3");
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
        });
        getContentPane().add(btn3);
        btn3.setBounds(130, 290, 50, 48);

        btn4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn4.setText("4");
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4MouseClicked(evt);
            }
        });
        getContentPane().add(btn4);
        btn4.setBounds(30, 240, 50, 50);

        btn5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn5.setText("5");
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn5MouseClicked(evt);
            }
        });
        getContentPane().add(btn5);
        btn5.setBounds(80, 240, 50, 50);

        btn6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn6.setText("6");
        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn6MouseClicked(evt);
            }
        });
        getContentPane().add(btn6);
        btn6.setBounds(130, 240, 50, 50);

        btn7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn7.setText("7");
        btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn7MouseClicked(evt);
            }
        });
        getContentPane().add(btn7);
        btn7.setBounds(30, 190, 50, 50);

        btn8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn8.setText("8");
        btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn8MouseClicked(evt);
            }
        });
        getContentPane().add(btn8);
        btn8.setBounds(80, 190, 50, 50);

        btn9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn9.setText("9");
        btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn9MouseClicked(evt);
            }
        });
        getContentPane().add(btn9);
        btn9.setBounds(130, 190, 50, 50);

        soma.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        soma.setText("+");
        soma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                somaMouseClicked(evt);
            }
        });
        getContentPane().add(soma);
        soma.setBounds(180, 340, 50, 50);

        menos.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        menos.setText("-");
        menos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menosMouseClicked(evt);
            }
        });
        getContentPane().add(menos);
        menos.setBounds(180, 290, 50, 48);

        multiplica.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        multiplica.setText("*");
        multiplica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiplicaMouseClicked(evt);
            }
        });
        getContentPane().add(multiplica);
        multiplica.setBounds(180, 240, 50, 50);

        divide.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        divide.setText("/");
        divide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divideMouseClicked(evt);
            }
        });
        getContentPane().add(divide);
        divide.setBounds(180, 190, 50, 50);

        igual.setBackground(new java.awt.Color(0, 120, 193));
        igual.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        igual.setText("=");
        igual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                igualMouseClicked(evt);
            }
        });
        getContentPane().add(igual);
        igual.setBounds(230, 290, 50, 100);

        jButton4.setText("1/x");
        getContentPane().add(jButton4);
        jButton4.setBounds(230, 240, 50, 50);

        jButton29.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton29.setText("←");
        getContentPane().add(jButton29);
        jButton29.setBounds(30, 140, 50, 50);

        jButton30.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton30.setText(",");
        getContentPane().add(jButton30);
        jButton30.setBounds(130, 340, 50, 50);

        porcentagem.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        porcentagem.setText("%");
        porcentagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                porcentagemMouseClicked(evt);
            }
        });
        getContentPane().add(porcentagem);
        porcentagem.setBounds(230, 190, 50, 50);

        jButton44.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton44.setText("√");
        getContentPane().add(jButton44);
        jButton44.setBounds(230, 140, 50, 50);

        jButton45.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jButton45.setText("±");
        getContentPane().add(jButton45);
        jButton45.setBounds(180, 140, 50, 50);

        jButton46.setText("M-");
        getContentPane().add(jButton46);
        jButton46.setBounds(230, 90, 50, 48);

        jButton47.setText("CE");
        getContentPane().add(jButton47);
        jButton47.setBounds(80, 140, 50, 50);

        jButton49.setText("MC");
        getContentPane().add(jButton49);
        jButton49.setBounds(30, 90, 50, 48);

        jButton50.setText("MR");
        getContentPane().add(jButton50);
        jButton50.setBounds(80, 90, 50, 48);

        jButton51.setText("MS");
        getContentPane().add(jButton51);
        jButton51.setBounds(130, 90, 50, 48);

        jButton52.setText("M+");
        getContentPane().add(jButton52);
        jButton52.setBounds(180, 90, 50, 48);

        jMenu1.setText("Exibir");

        jRadioButtonMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK));
        buttonGroup1.add(jRadioButtonMenuItem1);
        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Padrão");
        jMenu1.add(jRadioButtonMenuItem1);

        jRadioButtonMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_MASK));
        buttonGroup1.add(jRadioButtonMenuItem2);
        jRadioButtonMenuItem2.setText("Cientifíca");
        jMenu1.add(jRadioButtonMenuItem2);

        jRadioButtonMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_MASK));
        buttonGroup1.add(jRadioButtonMenuItem3);
        jRadioButtonMenuItem3.setText("Programador");
        jMenu1.add(jRadioButtonMenuItem3);

        jRadioButtonMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_MASK));
        buttonGroup1.add(jRadioButtonMenuItem4);
        jRadioButtonMenuItem4.setText("Estatistica");
        jMenu1.add(jRadioButtonMenuItem4);
        jMenu1.add(jSeparator1);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Histórico");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Agrupamento de dígitos");
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator2);

        jRadioButtonMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        buttonGroup2.add(jRadioButtonMenuItem5);
        jRadioButtonMenuItem5.setSelected(true);
        jRadioButtonMenuItem5.setText("Básico");
        jMenu1.add(jRadioButtonMenuItem5);

        jRadioButtonMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        buttonGroup2.add(jRadioButtonMenuItem6);
        jRadioButtonMenuItem6.setText("Conversão de unidades");
        jMenu1.add(jRadioButtonMenuItem6);

        jRadioButtonMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        buttonGroup2.add(jRadioButtonMenuItem7);
        jRadioButtonMenuItem7.setText("Cálculo de data");
        jMenu1.add(jRadioButtonMenuItem7);

        jMenu4.setText("Planilhas");
        jMenu1.add(jMenu4);

        exibir.add(jMenu1);

        editar.setText("Editar");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Copiar");
        editar.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Colar");
        editar.add(jMenuItem4);
        editar.add(jSeparator3);

        jMenu2.setText("Histórico");
        editar.add(jMenu2);

        exibir.add(editar);

        ajuda.setText("Ajuda");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem5.setText("Exibir Ajuda");
        ajuda.add(jMenuItem5);
        ajuda.add(jSeparator4);

        Sobre.setText("Sobre a Calculadora");
        Sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobreActionPerformed(evt);
            }
        });
        ajuda.add(Sobre);

        exibir.add(ajuda);

        setJMenuBar(exibir);

        setSize(new java.awt.Dimension(325, 479));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void apagaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apagaMouseClicked
        txtPainel.setText("");
    }//GEN-LAST:event_apagaMouseClicked

    private void btn0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn0MouseClicked
        String valor = txtPainel.getText();
        txtPainel.setText(valor + "0");
    }//GEN-LAST:event_btn0MouseClicked

    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
        String valor = txtPainel.getText();
        txtPainel.setText(valor + "1");
    }//GEN-LAST:event_btn1MouseClicked

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseClicked
        String valor = txtPainel.getText();
        txtPainel.setText(valor + "2");
    }//GEN-LAST:event_btn2MouseClicked

    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseClicked
        String valor = txtPainel.getText();
        txtPainel.setText(valor + "3");
    }//GEN-LAST:event_btn3MouseClicked

    private void btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseClicked
        String valor = txtPainel.getText();
        txtPainel.setText(valor + "4");
    }//GEN-LAST:event_btn4MouseClicked

    private void btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseClicked
        String valor = txtPainel.getText();
        txtPainel.setText(valor + "5");
    }//GEN-LAST:event_btn5MouseClicked

    private void btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseClicked
        String valor = txtPainel.getText();
        txtPainel.setText(valor + "6");
    }//GEN-LAST:event_btn6MouseClicked

    private void btn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseClicked
        String valor = txtPainel.getText();
        txtPainel.setText(valor + "7");
    }//GEN-LAST:event_btn7MouseClicked

    private void btn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseClicked
        String valor = txtPainel.getText();
        txtPainel.setText(valor + "8");
    }//GEN-LAST:event_btn8MouseClicked

    private void btn9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseClicked
        String valor = txtPainel.getText();
        txtPainel.setText(valor + "9");
    }//GEN-LAST:event_btn9MouseClicked

    private void igualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_igualMouseClicked
        String valor = txtPainel.getText();
        System.out.println(">>>" + valor);
        Calculos calculos = new Calculos();
        String resultado = calculos.calculadora(valor);
        
        txtPainel.setText(resultado);
    }//GEN-LAST:event_igualMouseClicked

    private void somaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_somaMouseClicked
        String valor = txtPainel.getText();
        txtPainel.setText(valor + "+");
    }//GEN-LAST:event_somaMouseClicked

    private void menosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosMouseClicked
        String valor = txtPainel.getText();
        txtPainel.setText(valor + "-");
    }//GEN-LAST:event_menosMouseClicked

    private void multiplicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicaMouseClicked
        String valor = txtPainel.getText();
        txtPainel.setText(valor + "*");
    }//GEN-LAST:event_multiplicaMouseClicked

    private void divideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divideMouseClicked
        String valor = txtPainel.getText();
        txtPainel.setText(valor + "/");
    }//GEN-LAST:event_divideMouseClicked

    private void SobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobreActionPerformed
        new Sobre().setVisible(true);
    }//GEN-LAST:event_SobreActionPerformed

    private void porcentagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_porcentagemMouseClicked

    }//GEN-LAST:event_porcentagemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Sobre;
    private javax.swing.JMenu ajuda;
    private javax.swing.JButton apaga;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton divide;
    private javax.swing.JMenu editar;
    private javax.swing.JMenuBar exibir;
    private javax.swing.JButton igual;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem6;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JButton menos;
    private javax.swing.JButton multiplica;
    private javax.swing.JButton porcentagem;
    private javax.swing.JButton soma;
    private javax.swing.JTextPane txtPainel;
    // End of variables declaration//GEN-END:variables
}
